### ISSUE TITLE
release包中没有提供daemon.exe?

### ISSUE THREAD

**Issue by justin201802** [ragnaroks/Wind#3]
https://github.com/ragnaroks/Wind/releases/tag/v2.5.5
这个release版本的包中没有readme中提到的daemon.exe，没法安装成service服务。
能否打包的时候带上这个daemon.exe？

**Comment by ragnaroks** [comment]
改名为“wind.exe”了，可能是忘记改readme

**Comment by justin201802** [comment]
感谢， 问题解决了。
