### ISSUE TITLE
Release v2.5.6的SHA1匹配错误

### ISSUE THREAD

**Issue by justin201802** [ragnaroks/Wind#4]
正确的SHA1如下：
wind-runtime.7z
c32cab384f704d4bd772b3f9e6ec0b22d5d159ec 
windctl-runtime.7z
c7ff00097852c4849e8052bbae84e7e13312a944 

在Release说明中，这2个文件的SHA1错位了。

**Comment by ragnaroks** [comment]
感谢提醒，已更新
